server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BLQZ/cursoMicroservicios
          deleteUntrackedBranches: true
          default-label: main
          force-pull: false